-- 1. Tabla de Usuarios
-- La aplicación usa EF Core y busca por defecto la tabla "Usuarios"
CREATE TABLE IF NOT EXISTS "Usuarios" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" TEXT NOT NULL,
    "PasswordHash" TEXT NOT NULL,
    "Role" TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Usuarios_Email" ON "Usuarios" ("Email");

-- 2. Tabla de pedidos
-- Configurada en minúsculas explícitas en el DbContext
-- 'isactive' se usa para borrado lógico (True = Visible)
CREATE TABLE IF NOT EXISTS pedidos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numeropedido TEXT NOT NULL,
    cliente TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    total DECIMAL(10,2) NOT NULL,
    estado TEXT NOT NULL,
    isactive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS "ix_pedidos_numeropedido" ON pedidos (numeropedido);

-- NOTA:
-- No es necesario insertar usuarios manualmente.
-- Al iniciar el Backend (MetricaReto.API), el 'DbInitializer' detecta si la tabla Usuarios está vacía
-- y crea automáticamente:
--   admin@metrica.com / admin123
--   user@email.com / 123456
